version: '3'
services:
  web:
    container_name: web
    build: .
    ports:
      - 6543:6543
    volumes:
      - .:/code
    stdin_open: true
    tty: true

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
       - POSTGRES_USER=root
       - POSTGRES_PASSWORD=password
       - APP_DB_USER=docker
       - APP_DB_PASS=docker
       - APP_DB_NAME=docker
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      

